### ISSUE TITLE
Can you share the dataset, thank you

### ISSUE THREAD

**Issue by zhaigang2333** [Sarathismg/GSNE#1]
want to understand the structure of dataset,thank you

**Comment by Sarathismg** [comment]
Thanks for your interest in our work. Unfortunately, we cannot share the dataset since we are not the owners of this dataset. Furthermore, this may also raise some privacy concerns. However, we will very soon provide a sample dataset and the preprocessing steps to give a better idea of the dataset structure as a part of our upcoming journal publication.
